version: "3"
services:
  postgres:
    image: "postgres:12.3"
    environment:
      - "POSTGRES_USER=smidle"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=smidle-db"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
