apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - smidle-restapi.yaml
  - smidle-frontend.yaml
  - metrics-server.yaml
  - sealed-secrets.yaml
configMapGenerator:
  - name: backendconfig
    files:
      - rest-api.properties
      - ca-certificate-postgresql.crt
