apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - smidle-deployment.yaml
  - smidle-service.yaml
secretGenerator:
  - name: docker-registries
    files:
      - .dockerconfigjson=docker-registry-auth.json
    type: kubernetes.io/dockerconfigjson
