apiVersion: apps/v1
kind: Deployment
metadata:
  name: smidle
  labels:
    app: smidle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smidle
  template:
    metadata:
      labels:
        app: smidle
    spec:
      imagePullSecrets:
        - name: docker-registries
      containers:
        - name: smidle-rest-api
          image: docker.pkg.github.com/smartsquaregmbh/smidle/smidle-rest-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
