spring:
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: smidle
    password: postgres

webhooks:
  secret: "1.k%Q[UA>^{4Z?}~VD7="
