name: CD

on: push

jobs:
  check-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK 14
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 14

    - name: Setup Gradle cache
      uses: actions/cache@v2.0.0
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('rest-api/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Check
      run: ./rest-api/gradlew -p rest-api check

    - name: Upload restapi reports
      uses: actions/upload-artifact@v2.0.1
      if: failure()
      with:
        name: Restapi Reports
        path: rest-api/build/reports

  check-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setupt kustomize
        uses: imranismail/setup-kustomize@v1.3.0
        with:
          kustomize-version: "3.6.1"

      - name: Render Deployment Manifests
        run: kustomize build $GITHUB_WORKSPACE/deployment > deployment.yaml

      - name: Deployment Check
        uses: instrumenta/kubeval-action@master
        with:
          files: "deployment.yaml"

  publish-backend:
    needs: [check-backend]
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 14
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 14

      - name: Setup Gradle Cache
        uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('rest-api/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Backend
        run: ./rest-api/gradlew -p rest-api jibDockerBuild

      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: docker push docker.pkg.github.com/smartsquaregmbh/smidle/smidle-rest-api:latest

  deploy:
    needs: [publish-backend, check-deployment]
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setupt kustomize
        uses: imranismail/setup-kustomize@v1.3.0
        with:
          kustomize-version: "3.6.1"

      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@v1.8.0
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} #?
        with:
          args: kubernetes cluster kubeconfig show leonies-cluster > $GITHUB_WORKSPACE/.kubeconfig

      - name: Deploy DigitalOcean Kubernetes
        run: kustomize build $GITHUB_WORKSPACE/deployment | kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f -

      - name: Cleanup unused configmaps and secrets
        run: kustomize build $GITHUB_WORKSPACE/deployment | kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f - --prune -l author=kustomize

  delete-old-images:
    needs: [publish-backend]
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - name: Delte restapi
        uses: actions/delete-package-versions@v1
        with:
          package-name: "smidle-rest-api"
